changelog:
  file: CHANGELOG.md
  types:
    feat: Features
    fix: Bug Fixes
    docs: Documentation
    refactor: Code Refactoring
    perf: Performance Improvements
    test: Tests
    build: Build System
    ci: Continuous Integration
    chore: Chores
  includeHash: true
  includeDate: true
  includeAuthor: false

version:
  files: []
  tagPrefix: ""
  tagMessage: "Release {version}"
  commitMessage: "release: {version}"

commits:
  conventional: true
  allowCustomTypes: true

git:
  push: true
  pushTags: true
  signTags: true
  signCommits: true
